spring:
  profiles:
    active: dev   #应用application-dev的配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guns?useUnicode=true&characterEncoding=utf-8&useSSL=false   #连接到linux服务器
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource     #阿里巴巴Driud连接池
    platform: mysql
#    schema: classpath:import.sql (无效)
#    data: classpath:import.sql  (无效)
  jpa:
    hibernate:
      ddl-auto: create   #建表方式
    show-sql: true   #显示sql语句
    #启动时是否初始化数据库-hibernate
#    generate-ddl: false  (无效)
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect   #设置InnoDB引擎（不设置默认位MyISAM）
  resources:
  #用于描述静态资源的存放位置
    static-locations: classpath:/static
  mvc:
   #用于阐述HTTP请求地址,在SpringBoot中，默认配置的/**映射到/static。
    static-path-pattern: /**
management:
  endpoints:
    web:
      exposure:
        include: bean


