spring:
  profiles:
    active: dev   #应用application-dev的配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guns?useUnicode=true&characterEncoding=utf-8&useSSL=false   #连接到linux服务器
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource   #阿里巴巴Driud连接池
  jpa:
    hibernate:
      ddl-auto: update   #建表方式
    show-sql: true   #显示sql语句
  resources:
    static-locations: classpath:/static   #用于描述静态资源的存放位置
  mvc:
    static-path-pattern: /**  #用于阐述HTTP请求地址,在SpringBoot中，默认配置的/**映射到/static。



